src/SG/AdminBundle/Entity/Socio.php
<?php

namespace SG\AdminBundle\Entity;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * SG\AdminBundle\Entity\Socio
 * @ORM\Table(name="socio")
 * @ORM\Entity(repositoryClass="SG\AdminBundle\Entity\SocioRepository")
 * @ORM\HasLifecycleCallbacks
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
 */
class Socio {
    /**
     * @var integer $id
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;

    /**
     * @var string $nroDocumento
     * @ORM\Column(name="nro_documento", type="string",length=15, nullable=true)
     */
    protected $nroDocumento;

    /**
     * @var string $cuit
     * @ORM\Column(name="cuit", type="string",length=15, nullable=true)
     */
    protected $cuit;

    /**
     * @var string $nombre
     * @ORM\Column(name="nombre", type="string", nullable=false)
     * @Assert\NotBlank()
     */
    protected $nombre;

    /**
     * @var string $apellido
     * @ORM\Column(name="apellido", type="string", nullable=false)
     * @Assert\NotBlank()
     */
    protected $apellido;

    /**
     * @var date $fechaNacimiento
     * @ORM\Column(name="fecha_nacimiento", type="date", nullable=true)
     */
    protected $fechaNacimiento;

    /**
     * @var date $fechaBaja
     * @ORM\Column(name="fecha_baja", type="date", nullable=true)
     */
    protected $fechaBaja;

    /**
     * @var integer $saldoInicial
     * @ORM\Column(name="saldo_inicial", type="decimal", scale=2, nullable=true )
     */
    protected $saldoInicial;

    /**
     * @var string $direccion
     * @ORM\Column(name="direccion", type="string", nullable=true)
     */
    protected $direccion;

    /**
     * @var string $telefono
     * @ORM\Column(name="telefono", type="string", nullable=true)
     */
    protected $telefono;

    /**
     * @var string $contacto
     * @ORM\Column(name="contacto", type="string", nullable=true)
     */
    protected $contacto;

    /**
     * @ORM\ManyToOne(targetEntity="SG\ConfigBundle\Entity\Localidad")
     * @ORM\JoinColumn(name="localidad_id", referencedColumnName="id")
     */
    protected $localidad;

    /**
     * @var string $celular
     * @ORM\Column(name="celular", type="string", nullable=true)
     */
    protected $celular;

    /**
     * @var string $email
     * @ORM\Column(name="email", type="string", nullable=true)
     */
    protected $email;

    /**
     * @ORM\Column(name="activo", type="boolean", nullable=true)
     */
    protected $activo = true;

    /**
     * @ORM\ManyToMany(targetEntity="SG\ConfigBundle\Entity\Empresa")
     * @ORM\JoinTable(name="empresas_x_socio",
     *      joinColumns={@ORM\JoinColumn(name="socio_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="empresa_id", referencedColumnName="id", onDelete="RESTRICT")}
     * )
     */
    private $empresas;

    /**
     * @ORM\OneToMany(targetEntity="SG\AdminBundle\Entity\Empleado", mappedBy="socio",cascade={"persist", "remove"})
     * @ORM\OrderBy({"apellido" = "ASC","nombre" = "ASC"})
     */
    protected $empleados;

    /**
     * @ORM\OneToMany(targetEntity="SG\AdminBundle\Entity\Vehiculo", mappedBy="socio",cascade={"persist", "remove"})
     * @ORM\OrderBy({"dominio" = "ASC"})
     */
    protected $vehiculos;

    /**
     * @ORM\OneToMany(targetEntity="SG\AdminBundle\Entity\Deuda", mappedBy="socio",cascade={"persist", "remove"})
     * @ORM\OrderBy({"fechaVto"="ASC"})
     */
    protected $deudas;

    /**
     * @ORM\Column(name="deletedAt", type="datetime", nullable=true)
     */
    private $deletedAt;

    /**
     * @var datetime $created
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @var User $createdBy
     * @Gedmo\Blameable(on="create")
     * @ORM\ManyToOne(targetEntity="SG\ConfigBundle\Entity\Usuario")
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
     */
    private $createdBy;

    /**
     * @var datetime $updated
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $updated;

    /**
     * @var User $updatedBy
     * @Gedmo\Blameable(on="update")
     * @ORM\ManyToOne(targetEntity="SG\ConfigBundle\Entity\Usuario")
     * @ORM\JoinColumn(name="updated_by", referencedColumnName="id")
     */
    private $updatedBy;

    public function __toString() {
        return $this->getNombreCompleto();
    }

    public function getNombreCompleto() {
        return $this->apellido . ', ' . $this->nombre;
    }

    public function getTelefonos() {
        $tel = $this->telefono;
        if ($tel != '')
            $tel = $tel . ' / ' . $this->celular;
        else
            $tel = $this->celular;
        return $tel;
    }

    public function getDireccionTxt() {
        return $this->direccion . ' - ' . $this->localidad;
    }

    public function getSaldo() {
        $saldo = 0;
        foreach ($this->getDeudas() as $deuda) {
            if ($deuda->getVencido())
                $saldo = $saldo + $deuda->getSaldo();
        }
        return $saldo;
    }

    public function getListaDeudas() {
        $deudas = new \Doctrine\Common\Collections\ArrayCollection();
        foreach ($this->getDeudas() as $deuda) {
            if ($deuda->getConcepto()->getTipo() != 'L') {
                $deudas->add($deuda);
            }
        }
        return $deudas;
    }

    /**
     * Constructor
     */
    public function __construct() {
        $this->deudas = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set nroDocumento
     *
     * @param string $nroDocumento
     * @return Socio
     */
    public function setNroDocumento($nroDocumento) {
        $this->nroDocumento = $nroDocumento;

        return $this;
    }

    /**
     * Get nroDocumento
     *
     * @return string
     */
    public function getNroDocumento() {
        return $this->nroDocumento;
    }

    /**
     * Set cuit
     *
     * @param string $cuit
     * @return Socio
     */
    public function setCuit($cuit) {
        $this->cuit = $cuit;

        return $this;
    }

    /**
     * Get cuit
     *
     * @return string
     */
    public function getCuit() {
        return $this->cuit;
    }

    /**
     * Set nombre
     *
     * @param string $nombre
     * @return Socio
     */
    public function setNombre($nombre) {
        $this->nombre = $nombre;

        return $this;
    }

    /**
     * Get nombre
     *
     * @return string
     */
    public function getNombre() {
        return $this->nombre;
    }

    /**
     * Set apellido
     *
     * @param string $apellido
     * @return Socio
     */
    public function setApellido($apellido) {
        $this->apellido = $apellido;

        return $this;
    }

    /**
     * Get apellido
     *
     * @return string
     */
    public function getApellido() {
        return $this->apellido;
    }

    /**
     * Set fechaNacimiento
     *
     * @param \DateTime $fechaNacimiento
     * @return Socio
     */
    public function setFechaNacimiento($fechaNacimiento) {
        $this->fechaNacimiento = $fechaNacimiento;

        return $this;
    }

    /**
     * Get fechaNacimiento
     *
     * @return \DateTime
     */
    public function getFechaNacimiento() {
        return $this->fechaNacimiento;
    }

    /**
     * Set fechaBaja
     *
     * @param \DateTime $fechaBaja
     * @return Socio
     */
    public function setFechaBaja($fechaBaja) {
        $this->fechaBaja = $fechaBaja;

        return $this;
    }

    /**
     * Get fechaBaja
     *
     * @return \DateTime
     */
    public function getFechaBaja() {
        return $this->fechaBaja;
    }

    /**
     * Set saldoInicial
     *
     * @param string $saldoInicial
     * @return Socio
     */
    public function setSaldoInicial($saldoInicial) {
        $this->saldoInicial = $saldoInicial;

        return $this;
    }

    /**
     * Get saldoInicial
     *
     * @return string
     */
    public function getSaldoInicial() {
        return $this->saldoInicial;
    }

    /**
     * Set direccion
     *
     * @param string $direccion
     * @return Socio
     */
    public function setDireccion($direccion) {
        $this->direccion = $direccion;

        return $this;
    }

    /**
     * Get direccion
     *
     * @return string
     */
    public function getDireccion() {
        return $this->direccion;
    }

    /**
     * Set telefono
     *
     * @param string $telefono
     * @return Socio
     */
    public function setTelefono($telefono) {
        $this->telefono = $telefono;

        return $this;
    }

    /**
     * Get telefono
     *
     * @return string
     */
    public function getTelefono() {
        return $this->telefono;
    }

    /**
     * Set celular
     *
     * @param string $celular
     * @return Socio
     */
    public function setCelular($celular) {
        $this->celular = $celular;

        return $this;
    }

    /**
     * Get celular
     *
     * @return string
     */
    public function getCelular() {
        return $this->celular;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Socio
     */
    public function setEmail($email) {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail() {
        return $this->email;
    }

    /**
     * Set activo
     *
     * @param boolean $activo
     * @return Socio
     */
    public function setActivo($activo) {
        $this->activo = $activo;

        return $this;
    }

    /**
     * Get activo
     *
     * @return boolean
     */

src/SG/AdminBundle/Form/SocioType.php
<?php

namespace SG\AdminBundle\Form;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use SG\ConfigBundle\Form;

class SocioType extends AbstractType {

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder
                ->add('savenew', 'hidden', array('mapped' => false, 'required' => false))
                ->add('nombre', null, array('label' => 'Nombre:', 'required' => true))
                ->add('apellido', null, array('label' => 'Apellido:', 'required' => true))
                ->add('nroDocumento', null, array('label' => 'Nº Documento:', 'required' => false))
                ->add('cuit', null, array('label' => 'CUIT:', 'required' => false))
                ->add('fechaNacimiento', 'date', array('widget' => 'single_text', 'label' => 'Fecha Nacimiento:',
                    'format' => 'dd-MM-yyyy', 'required' => false))
                ->add('direccion', null, array('label' => 'Dirección:', 'required' => false))
                ->add('telefono', null, array('label' => 'Teléfono:', 'required' => false))
                ->add('contacto', null, array('label' => 'Contacto:', 'required' => false))
                ->add('localidad', 'entity', array('class' => 'ConfigBundle:Localidad'))
                ->add('celular', null, array('label' => 'Celular:', 'required' => false))
                ->add('email', null, array('label' => 'Email:', 'required' => false))
                ->add('activo', null, array('label' => 'Activo:', 'required' => false))
                //domicilios laborales
                ->add('empresas', 'entity', array(
                    'class' => 'ConfigBundle:Empresa',
                    'label' => 'Empresas:',
                    'multiple' => true,
                    'required' => false,
                ))
        ;
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver) {
        $resolver->setDefaults(array(
            'data_class' => 'SG\AdminBundle\Entity\Socio'
        ));
    }

    /**
     * @return string
     */
    public function getName() {
        return 'sg_adminbundle_socio';
    }

}

src/SG/AdminBundle/Resources/views/Socio/_liquidaciones_list.html.twig
<div class="box-body table-responsive">
    <table id="tablelist" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th class="nosort" style="width:15px">&nbsp;#</th>
                <th class="nosort" style="width:70px">Fecha</th>
                <th class="nosort" style="width:15px">Hora</th>
                <th class="nosort" >Descripción</th>
                <th class="nosort center" style="width:100px">Monto</th>
                <th class="nosort" style="width:20px"></th>
                <th class="nosort" style="width:20px"></th>
            </tr>
        </thead>
        <tbody>                     
            {% if liquidaciones|length>0 %}
                {% set total = 0 %}
            {% for movimiento in liquidaciones %}
                {% set total = total + movimiento.detalleLiquidacion.importe %}
                <tr class="odd gradeX">
                    <td> {{ loop.index }} </td>
                    <td>{{ movimiento.fecha|date('d-m-Y') }}</td>
                    <td>{{ movimiento.fecha|date('H:i') }}</td>
                    <td> {{movimiento.descripcion}} </td>
                    <td class="alignright">{{movimiento.detalleLiquidacion.importe|number_format(2,'.',',')}}  </td>                    
                    <td><button type="button" class="vermas" id="{{movimiento.id}}" style="margin: 0" title="Ver detalle" ><i class="fa fa-caret-down"></i></button></td>                    
                    <td><button type="button" class="comprobante" data-url="{{ path('caja_print_movimiento', { 'id': movimiento.id })  }}" style="margin: 0" title="Imprimir" ><i class="fa fa-file-text-o"></i></button></td>                    
                </tr>
                <tr class="even" id="tr_detalle_{{movimiento.id}}" data-tipo="{{movimiento.tipo}}">
                    <td></td>
                    <td colspan="5" class="datos_detalle"></td>
                    <td></td>
                </tr>
            {% endfor %}
            {% else %}
                <tr>
                    <th colspan="7" class="aligncenter"> -- SIN MOVIMIENTOS --</th>
                </tr>
            {% endif %}            
        </tbody>
        <tfoot>
            <tr>
                <th colspan="4" class="alignright">Total Liquidado: </th>
                <th class="alignright">{{ total|number_format(2,'.',',') }}</th>
                <th colspan="2"></th>
            </tr>
        </tfoot>
    </table>
</div>    

src/SG/AdminBundle/Resources/views/Socio/_partial_datosCtaCte.html.twig
{%if 'socio-abm-edit' in app.user.perfil.permisos %}
     {% set url =  path('socio_abm_edit', { 'id': socio.id }) %}
{% elseif 'socio-abm-show' in app.user.perfil.permisos  %}
    {% set url =  path('socio_abm_show', { 'id': socio.id }) %}
{% endif %}
<a href="{{ url }}" class="link-socio btn btn-xs btn-info" title="Más Datos del Socio" data-toggle="tooltip"><i class="ion ion-person"></i></a>&nbsp;
<span><strong>DNI:</strong> {{ socio.nroDocumento }}</span>

<span><strong>Dirección:</strong> {{ socio.direccion }}</span>
<span><strong>Teléfonos:</strong> {{ socio.telefonos }}</span>
<span><strong>Localidad:</strong> {{ socio.localidad }}</span>
<a href="{{ path('export_estado_deuda', { 'id': socio.id, 'estado' : vencido }) }}"  class="pull-right btn btn-default" target="_blank" title="Exportar" data-toggle="tooltip"><i class="fa fa-file-excel-o"></i>&nbsp;&nbsp;Exportar</a>
<a href="{{ path('print_estado_deuda', { 'id': socio.id, 'estado' : vencido }) }}"  class="pull-right btn btn-default" target="_blank" title="Imprimir" data-toggle="tooltip"><i class="fa fa-print"></i>&nbsp;&nbsp;Imprimir</a>
<hr>

<div class="table-responsive">
    <table id="tabledeuda" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th class="no-sort">#</th>
                <th class="no-sort">Fecha</th>
                <th class="no-sort">Concepto</th>
                <th>Vencimiento</th>
                <th class="no-sort">Importe</th>
                <th class="no-sort">Interés</th>
                <th class="no-sort">Total</th>
                <th class="no-sort" style="background:#868686;padding:1px;"></th>
                <th class="no-sort">Pago</th>
                <th class="no-sort">SALDO</th>
                <th class="no-sort aligncenter" style="width:8%;"></th>
            </tr>
        </thead>
        <tbody>
            {% set importe,interes,total, aux = 0,0,0,0 %}
            
            {% for deuda in socio.deudas if deuda.concepto.tipo!='L' %}  
                {% if (vencido=='true' and deuda.vencido) or vencido=='false'  %}                                                
                {% set importe,interes,total = importe+deuda.monto , interes+deuda.mora, total+deuda.saldo %}                
                <tr class="odd gradeX">
                    <td>{{ loop.index }}</td>
                    <td>{{ deuda.created|date('d-m-Y') }}</td>
                    <td>{{ deuda.concepto }} {% if deuda.detalle %} - {% endif %} {{ deuda.detalle }} </td>
                    <td {% if deuda.vencido %} class="red" {% endif %} > <span class="hidden">{{ deuda.fechaVto|date('Ymd') }}</span>{{ deuda.fechaVto|date('d-m-Y') }}</td>
                    <td class="alignright">{{ deuda.monto|number_format(2,'.',',') }}</td>
                    <td class="alignright">{{ deuda.mora|number_format(2,'.',',') }}</td>
                    <td class="alignright">{{ (deuda.monto+deuda.mora)|number_format(2,'.',',') }}</td>
                    <td style="background:#868686;padding:1px;"></td>
                    <td>{%if deuda.ultimoPago %}{{deuda.ultimoPago|date('d-m-Y')}}{% endif %}
                        <!--<a href="#" data-toggle="tooltip" title="Registrar el Pago"> &nbsp; <i class="fa fa-arrow-right"></i> <i class="fa fa-money"></i></a>-->                        
                    </td>
                    <td class="alignright {% if deuda.vencido %} red {% endif %}">
                        {{deuda.saldo|number_format(2,'.',',')}} 
                    </td>
                    <td>
                        {%if 'socio-ctacte-delete' in app.user.perfil.permisos and deuda.pagos|length ==0 %}
                        <form action="{{ path('socio_delete_deuda', { 'id': deuda.id }) }}" method="post" class="form-delete-inlist">
                          
                            {{ form_widget(deleteForms[deuda.id]) }}
                            <button type="button" title="Eliminar" class="btn-inlist btn-del-deuda" onclick="if (!confirm('Desea eliminar este Item?')) return false;" data-toggle="tooltip"><i class="fa fa-trash-o"></i></button>
                        </form>
                            &nbsp;
                        {% endif %}
                         <!-- SHOW -->
                        <button class="deuda-show-modal btn-inlist" data-url="{{path('deuda_show', {'id':deuda.id, 'mora': deuda.mora })}}" data-idx='{{ loop.index }}' title="Ver detalle" ><i class="fa fa-file-text-o"></i></button>

                    </td>
                </tr>
                {% endif %}
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <th colspan="4"></th>
                <th class="alignright">{{importe|number_format(2,'.',',')}}</th>
                <th class="alignright">{{interes|number_format(2,'.',',')}}</th>
                <th class="alignright">{{(importe+interes)|number_format(2,'.',',')}}</th>
                <th style="background:#868686;padding:1px;"></th>
                <th class="alignright">Vencido</th>
                <th class="alignright {% if socio.saldo>0 %} red {% endif %}">{{socio.saldo|number_format(2,'.',',')}}</th>
            </tr>
        </tfoot>
            
    </table>
</div>

src/SG/AdminBundle/Resources/views/Socio/list.html.twig
{% extends "AdminBundle::layout.html.twig" %}

{% block contentheader %}
    <h1> Socios</h1>
{% endblock %}

{% block content %}
    {% include "AdminBundle::notification.html.twig" %}

    <div class='row'>
        <div class='col-md-12'>
            <div class='box box-solid box-primary'>
                <div class='box-header'>
                    <h3 class='box-title'><i class="ion ion-person-stalker" style="font-size:24px"></i> &nbsp;Administración</h3>
                </div><!-- /.box-header -->
                <div class='box-body pad'>
                    <div class="clearfix">
                        <form action="{{ path('socio_abm') }}" id="search-empresa" class="form-horizontal">
                            <div class="form-group">
                                <label for="empresa" class="col-md-1 control-label">EMPRESA:</label>
                                <div class="col-md-4">
                                    <select name="empresa" id="select-empresa" class="form-control">
                                        <option value=""> Todas</option>
                                        {% for emp in empresas %}
                                            <option value="{{ emp.id }}" {% if empresa == emp.id %} selected {% endif %}> {{ emp.nombre }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="pull-right">
                                    {%if 'socio-abm-new' in app.user.perfil.permisos %}
                                        <a style="margin-right:25px" class="btn btn-warning " href="{{ path('socio_abm_new') }}" data-toggle="tooltip" title="Agregar Nuevo"><i class="ion ion-person-add" style="font-size:20px"></i> &nbsp;Agregar</a>
                                    {% endif %}
                                </div>

                            </div>
                        </form>

                    </div>
                    <div class="box-body table-responsive">
                        <table id="tablelist" class="table table-bordered table-hover tablelist">
                            <thead>
                                <tr>                                
                                    <th>Apellido y Nombre</th>
                                    <th>DNI</th>                                
                                    <th>CUIT</th>                                
                                    <th>Teléfonos</th>
                                    <th>Activo</th>
                                    <th>Saldo</th>
                                    <th class="nosort" style="width: 120px"> <a class="btn btn-sm btn-default" href="{{ path('socio_print_listado',{'empresa':empresa}) }}" target="_blank"><i class="fa fa-print"></i> &nbsp;Listado</a> </th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for entity in entities %}
                                    <tr>
                                        <td>{{ entity.nombreCompleto }}</td>
                                        <td>{{ entity.nroDocumento }}</td>
                                        <td>{{ entity.cuit }}</td>
                                        <td>{{ entity.telefonos }}</td>
                                        <td>{% if entity.activo %} <i class="fa fa-check"></i> {% else %} <i class="fa fa-close"></i> {% endif %} </td>
                                        <td class="alignright">{{ entity.saldo|number_format(2,'.',',')}}</td>
                                        <td class="link-actions">
                                            {%if 'socio-abm-edit' in app.user.perfil.permisos %}
                                                <a href="{{ path('socio_abm_edit', { 'id': entity.id }) }}" title="Editar Datos" data-toggle="tooltip"><i class="fa fa-edit"></i></a>&nbsp;
                                                {% else %}
                                                <a href="{{ path('socio_abm_show', { 'id': entity.id }) }}" title="Ver Datos" data-toggle="tooltip"><i class="fa fa-file-o"></i></a>&nbsp;
                                                {% endif %}
                                                {%if 'socio-abm-delete' in app.user.perfil.permisos %}
                                                <form action="{{ path('socio_abm_delete', { 'id': entity.id }) }}" method="post" class="form-delete-inlist">
                                                    <input type="hidden" name="_method" value="DELETE" />
                                                    {{ form_widget(deleteForms[entity.id]) }}
                                                    <button type="submit" title="Eliminar" class="btn-inlist" onclick="if (!confirm('Desea eliminar este Socio?'))
                                                                return false;" data-toggle="tooltip"><i class="fa fa-trash-o"></i></button>
                                                </form>
                                            {% endif %}
                                            &nbsp;&nbsp;<a href="{{ path('socio_ctacte', { 'id': entity.id }) }}" title="Ver Estado de Deuda" data-toggle="tooltip"><i class="fa fa-list-alt"></i></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>

                </div>
            </div><!-- /.box -->
        </div><!-- /.col-->
    </div><!-- ./row -->
{% endblock %}
{% block page_javascript %}
    <script src="{{ asset('assets/js/tables.js') }}" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {            
            $('#select-empresa').on('change', function () {
                $('#search-empresa').submit();
            });
        });
    </script>  
{% endblock %}

src/SG/AdminBundle/Resources/views/Socio/listado.pdf.twig
<pdf>
    <dynamic-page page-size="A4-landscape" margin-left="70px" margin-right="40px" margin-top="40px" >
        <placeholders>
            <header>
                <div height="85px" width="100%">
                    <table>
                        <tr>
                            <td border.type="none">
                               <img ignore-error="true" src="{{logo}}" width="330px" height="70px" margin-bottom="5px"/> 
                            </td>
                            <td border.type="none" font-size="16px" text-align="center" vertical-align="bottom" padding-bottom="10px">Nómina de Socios
                            </td>    
                            <td border.type="none" font-size="7px" text-align="right" vertical-align="bottom" padding-bottom="5px">
                                <strong>Fecha y hora: </strong>{{'now'|date('d-m-Y H:i')}} 
                            </td>
                        </tr>
                    </table>

                    <div border.color="#D65200" height="2px" ></div>   
                 </div>                      
            </header>
            <footer>
                <div height="30px" width="100%" text-align="right">
                    <page-number />
                </div>
            </footer>
        </placeholders>
        
        <div height="10px"></div>
        {% if empresa %}
            <h4>EMPRESA: {{ empresa.nombre }}</h4>
        {% endif %}
        <div height="20px"></div>
        
        
        <table font-size="7px">
                <tr>
                    <td vertical-align="middle" padding-left="10px" height="20px"><strong>Nombre y Apellido</strong></td>
                    <td vertical-align="middle" padding-left="10px" width="2 cm"><strong>N° Documento</strong></td>
                    <td vertical-align="middle" padding-left="10px" width="1.5 cm"><strong>Fecha Nac.</strong></td>                                        
                    <td vertical-align="middle" padding-left="10px"><strong>Domicilio Particular</strong></td>
                    <td vertical-align="middle" padding-left="10px"><strong>Teléfonos</strong></td>
                    <td vertical-align="middle" padding-left="10px"><strong>Email</strong></td>
                    <td vertical-align="middle" padding-left="10px" width="2 cm"><strong>Localidad</strong></td>
                </tr>
                {% for socio in socios %}
                    <tr>
                        <td vertical-align="middle" padding-left="10px" height="20px">{{ socio.nombreCompleto }}</td>
                        <td vertical-align="middle" padding-left="10px">{{ socio.nroDocumento }}</td>
                        <td vertical-align="middle" padding-left="10px">{{ socio.fechaNacimiento|date('d/m/Y') }}</td>                                                
                        <td vertical-align="middle" padding-left="10px">{{ socio.direccion }}</td>
                        <td vertical-align="middle" padding-left="10px">{{ socio.telefonos }}</td>                        
                        <td vertical-align="middle" padding-left="10px">{{ socio.email }}</td>
                        <td vertical-align="middle" padding-left="10px">{{ socio.localidad }}</td>
                    </tr>
                {% endfor %}
        </table>

    </dynamic-page>
</pdf>