src/SG/AdminBundle/Entity/Vehiculo.php
<?php

namespace SG\AdminBundle\Entity;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * SG\AdminBundle\Entity\Vehiculo
 * @ORM\Table(name="vehiculo")
 * @ORM\Entity()
 * @ORM\HasLifecycleCallbacks
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
 */
class Vehiculo {
    /**
     * @var integer $id
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;

    /**
     * @var string $dominio
     * @ORM\Column(name="dominio", type="string", nullable=false)
     */
    protected $dominio;

    /**
     * @var string $modelo
     * @ORM\Column(name="modelo", type="string",nullable=true)
     */
    protected $modelo;

    /**
     * @var string $marca
     * @ORM\Column(name="marca", type="string", nullable=true)
     */
    protected $marca;

    /**
     * @var integer $anio
     * @ORM\Column(name="anio", type="integer", nullable=true)
     */
    protected $anio;

    /**
     * @var string $kilometros
     * @ORM\Column(name="kilometros", type="string", nullable=true)
     */
    protected $kilometros;

    /**
     * @var string $carga
     * @ORM\Column(name="carga", type="string", nullable=true)
     */
    protected $carga;

    /**
     * @ORM\OneToMany(targetEntity="SG\AdminBundle\Entity\Linea", mappedBy="vehiculo",cascade={"persist", "remove"}, orphanRemoval=true)
     */
    protected $lineas;

    /**
     * @ORM\ManyToOne(targetEntity="SG\AdminBundle\Entity\Socio", inversedBy="vehiculos")
     * @ORM\JoinColumn(name="socio_id", referencedColumnName="id", onDelete="SET NULL")
     */
    protected $socio;

    /**
     * @ORM\ManyToOne(targetEntity="SG\AdminBundle\Entity\Empleado", inversedBy="vehiculos")
     * @ORM\JoinColumn(name="empleado_id", referencedColumnName="id",onDelete="SET NULL")
     */
    protected $empleado;

    /**
     * @ORM\Column(name="asignado_al_socio", type="boolean", nullable=true)
     */
    protected $asignadoAlSocio = false;

    /**
     * @var datetime $created
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @var User $createdBy
     * @Gedmo\Blameable(on="create")
     * @ORM\ManyToOne(targetEntity="SG\ConfigBundle\Entity\Usuario")
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
     */
    private $createdBy;

    /**
     * @var datetime $updated
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $updated;

    /**
     * @var User $updatedBy
     * @Gedmo\Blameable(on="update")
     * @ORM\ManyToOne(targetEntity="SG\ConfigBundle\Entity\Usuario")
     * @ORM\JoinColumn(name="updated_by", referencedColumnName="id")
     */
    private $updatedBy;

    /**
     * @ORM\Column(name="deletedAt", type="datetime", nullable=true)
     */
    private $deletedAt;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    public function __toString() {
        return $this->getMarca() . ' ' . $this->getModelo() . ' ' . $this->getDominio();
    }

    public function getMarcaModeloDominio() {
        return $this->getMarca() . ' ' . $this->getModelo() . ' ' . $this->getDominio();
    }

    /**
     * Set dominio
     *
     * @param string $dominio
     * @return Vehiculo
     */
    public function setDominio($dominio) {
        $this->dominio = strtoupper($dominio);

        return $this;
    }

    /**
     * Get dominio
     *
     * @return string
     */
    public function getDominio() {
        return $this->dominio;
    }

    /**
     * Set modelo
     *
     * @param string $modelo
     * @return Vehiculo
     */
    public function setModelo($modelo) {
        $this->modelo = $modelo;

        return $this;
    }

    /**
     * Get modelo
     *
     * @return string
     */
    public function getModelo() {
        return $this->modelo;
    }

    /**
     * Set marca
     *
     * @param string $marca
     * @return Vehiculo
     */
    public function setMarca($marca) {
        $this->marca = $marca;

        return $this;
    }

    /**
     * Get marca
     *
     * @return string
     */
    public function getMarca() {
        return $this->marca;
    }

    /**
     * Set anio
     *
     * @param integer $anio
     * @return Vehiculo
     */
    public function setAnio($anio) {
        $this->anio = $anio;

        return $this;
    }

    /**
     * Get anio
     *
     * @return integer
     */
    public function getAnio() {
        return $this->anio;
    }

    /**
     * Set kilometros
     *
     * @param string $kilometros
     * @return Vehiculo
     */
    public function setKilometros($kilometros) {
        $this->kilometros = $kilometros;

        return $this;
    }

    /**
     * Get kilometros
     *
     * @return string
     */
    public function getKilometros() {
        return $this->kilometros;
    }

    /**
     * Set carga
     *
     * @param string $carga
     * @return Vehiculo
     */
    public function setCarga($carga) {
        $this->carga = $carga;

        return $this;
    }

    /**
     * Get carga
     *
     * @return string
     */
    public function getCarga() {
        return $this->carga;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     * @return Vehiculo
     */
    public function setCreated($created) {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime
     */
    public function getCreated() {
        return $this->created;
    }

    /**
     * Set updated
     *
     * @param \DateTime $updated
     * @return Vehiculo
     */
    public function setUpdated($updated) {
        $this->updated = $updated;

        return $this;
    }

    /**
     * Get updated
     *
     * @return \DateTime
     */
    public function getUpdated() {
        return $this->updated;
    }

    /**
     * Set createdBy
     *
     * @param \SG\ConfigBundle\Entity\Usuario $createdBy
     * @return Vehiculo
     */
    public function setCreatedBy(\SG\ConfigBundle\Entity\Usuario $createdBy = null) {
        $this->createdBy = $createdBy;

        return $this;
    }

    /**
     * Get createdBy
     *
     * @return \SG\ConfigBundle\Entity\Usuario
     */
    public function getCreatedBy() {
        return $this->createdBy;
    }

    /**
     * Set updatedBy
     *
     * @param \SG\ConfigBundle\Entity\Usuario $updatedBy
     * @return Vehiculo
     */
    public function setUpdatedBy(\SG\ConfigBundle\Entity\Usuario $updatedBy = null) {
        $this->updatedBy = $updatedBy;

        return $this;
    }

    /**
     * Get updatedBy
     *
     * @return \SG\ConfigBundle\Entity\Usuario
     */
    public function getUpdatedBy() {
        return $this->updatedBy;
    }

    /**
     * Set deletedAt
     *
     * @param \DateTime $deletedAt
     * @return Vehiculo
     */
    public function setDeletedAt($deletedAt) {
        $this->deletedAt = $deletedAt;

        return $this;
    }

    /**
     * Get deletedAt
     *
     * @return \DateTime
     */
    public function getDeletedAt() {
        return $this->deletedAt;
    }

    /**
     * Set socio
     *
     * @param \SG\AdminBundle\Entity\Socio $socio
     * @return Vehiculo
     */
    public function setSocio(\SG\AdminBundle\Entity\Socio $socio = null) {
        $this->socio = $socio;

        return $this;
    }

    /**
     * Get socio
     *
     * @return \SG\AdminBundle\Entity\Socio
     */
    public function getSocio() {
        return $this->socio;
    }

    /**
     * Set empleado
     *
     * @param \SG\AdminBundle\Entity\Empleado $empleado
     * @return Vehiculo
     */
    public function setEmpleado(\SG\AdminBundle\Entity\Empleado $empleado = null) {
        $this->empleado = $empleado;

        return $this;
    }

    /**
     * Get empleado
     *
     * @return \SG\AdminBundle\Entity\Empleado
     */
    public function getEmpleado() {
        return $this->empleado;
    }

    /**
     * Constructor
     */
    public function __construct() {
        $this->lineas = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add lineas
     *
     * @param \SG\AdminBundle\Entity\Linea $lineas
     * @return Vehiculo
     */
    public function addLinea(\SG\AdminBundle\Entity\Linea $lineas) {
        $lineas->setVehiculo($this);
        $this->lineas[] = $lineas;

        return $this;
    }

    /**
     * Remove lineas
     *
     * @param \SG\AdminBundle\Entity\Linea $lineas
     */
    public function removeLinea(\SG\AdminBundle\Entity\Linea $lineas) {
        $this->lineas->removeElement($lineas);
    }

    /**
     * Get lineas
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getLineas() {
        return $this->lineas;
    }

    public function getLineasHtml() {
        $html = '<ul class="ul-lineas">';
        foreach ($this->getLineas() as $linea) {
            $html = $html . '<li>' . $linea->getNombre() . ' [' . $linea->getKilometros() . ' km] </li>';
        }
        $html = $html . '</ul>';
        return $html;
    }

    public function getLineasTxt() {
        $txt = '';
        foreach ($this->getLineas() as $linea) {
            $txt = $txt . '<div><strong> • </strong>' . $linea->getNombre() . ' [' . $linea->getKilometros() . ' km] </div>';
        }
        return $txt;
    }

    /**
     * Set asignadoAlSocio
     *
     * @param boolean $asignadoAlSocio
     * @return Vehiculo
     */
    public function setAsignadoAlSocio($asignadoAlSocio) {
        $this->asignadoAlSocio = $asignadoAlSocio;

        return $this;
    }

    /**
     * Get asignadoAlSocio
     *
     * @return boolean
     */
    public function getAsignadoAlSocio() {
        return $this->asignadoAlSocio;
    }

src/SG/AdminBundle/Controller/VehiculoController.php
<?php

namespace SG\AdminBundle\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use SG\ConfigBundle\Controller\UtilsController;
use SG\AdminBundle\Entity\Vehiculo;
use SG\AdminBundle\Form\VehiculoType;

/**
 * Vehiculo controller.
 */
class VehiculoController extends Controller {

    public function renderVehiculoModalAction(Request $request) {
        $id = $request->get('id');
        $socioId = $request->get('socio');
        $em = $this->getDoctrine()->getManager();

        if ($id) {
            // EDIT
            $entity = $em->getRepository('AdminBundle:Vehiculo')->find($id);
            $urlAction = $this->generateUrl('vehiculo_update', array('id' => $id));
            $permiso = UtilsController::checkPermiso(array('vehiculo', 'abm', 'edit'));
            if (!$permiso) {
                // ir a la vista si no tiene permiso de edición
                $html = $this->renderView('AdminBundle:Vehiculo:_partial_show.html.twig',
                        array('entity' => $entity)
                );
                return new Response($html);
            }
        }
        else {
            // NEW
            $entity = new Vehiculo();
            $socio = $em->getRepository('AdminBundle:Socio')->find($socioId);
            $entity->setSocio($socio);
            $urlAction = $this->generateUrl('vehiculo_create');
            $permiso = UtilsController::checkPermiso(array('vehiculo', 'abm', 'new'));
        }
        if ($permiso) {
            $form = $this->createForm(new VehiculoType(), $entity, array(
                'action' => $urlAction, 'method' => 'POST',
            ));

            $html = $this->renderView('AdminBundle:Vehiculo:_partial_edit.html.twig',
                    array('entity' => $entity, 'form' => $form->createView(), 'urlaction' => $urlAction)
            );
        }
        else {
            $session = $this->get('session');
            $session->getFlashBag()->add('danger', 'Usted no posee los permisos necesarios para realizar esta acción');
            $html = $this->renderView('AdminBundle::form-notification.html.twig');
        }
        return new Response($html);
    }

    public function createAction(Request $request) {
        $entity = new Vehiculo();
        $form = $this->createForm(new VehiculoType(), $entity, array(
            'action' => $this->generateUrl('vehiculo_create'),
            'method' => 'POST',
        ));
        $form->handleRequest($request);
        $msg = 'No se pudo realizar esta operación.' . chr(13) . ' Verifique los datos ingresados.';
        $row = '';
        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            try {
                $em->persist($entity);
                $em->flush();
                // armar tr para reemplazar
                $row = $this->renderView('AdminBundle:Vehiculo:_partial_list_tr.html.twig',
                        array('vehiculo' => $entity)
                );
                // armar partial para reemplazar tabla empleados
                $partial = $this->renderView('AdminBundle:Empleado:_partial_list.html.twig',
                        array('entity' => $entity->getSocio())
                );
                $msg = 'OK';                
            }
            catch (\Exception $ex) {
                $msg = $ex->getMessage();
            }
        }
        $result = array('msg' => $msg, 'trhtml' => $row, 'partial' => $partial);
        return new Response(json_encode($result));
    }

    public function updateAction($id, Request $request) {
        $em = $this->getDoctrine()->getManager();
        $entity = $em->getRepository('AdminBundle:Vehiculo')->find($id);
        if (!$entity) {
            throw $this->createNotFoundException('No existe el Vehículo.');
        }

        $form = $this->createForm(new VehiculoType(), $entity, array(
            'action' => $this->generateUrl('vehiculo_update', array('id' => $id)),
            'method' => 'POST',
        ));
        $form->handleRequest($request);
        $msg = 'No se pudo realizar esta operación.' . chr(13) . ' Verifique los datos ingresados.';
        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            try {
                $em->persist($entity);
                $em->flush();
                // armar tr para reemplazar
                $row = $this->renderView('AdminBundle:Vehiculo:_partial_list_tr.html.twig',
                        array('vehiculo' => $entity)
                );
                // armar partial para reemplazar tabla empleados
                $partial = $this->renderView('AdminBundle:Empleado:_partial_list.html.twig',
                        array('entity' => $entity->getSocio())
                );
                $msg = 'OK';                
            }
            catch (\Exception $ex) {
                $msg = $ex->getMessage();
            }
        }
        $result = array('msg' => $msg, 'trhtml' => $row, 'partial' => $partial);
        return new Response(json_encode($result));
    }

    public function deleteAction($id) {
        $msg = 'OK';
        $partial = '';
        if (UtilsController::checkPermiso(array('vehiculo', 'abm', 'delete'))) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('AdminBundle:Vehiculo')->find($id);
            $socio = $entity->getSocio();
            $empleado = $entity->getEmpleado() ? true : false;
            try {
                $em->remove($entity);
                $em->flush();
                if ($empleado) {
                    // armar partial con datos de empleados
                    $partial = $this->renderView('AdminBundle:Empleado:_partial_list.html.twig',
                            array('entity' => $socio)
                    );
                }
            }
            catch (\Exception $ex) {
                $msg = $ex->getMessage();
            }
        }
        else {
            $msg = 'Usted no posee los permisos necesarios para realizar esta acción';
        }
        $result = array('msg' => $msg, 'partial' => $partial);
        return new Response(json_encode($result));
    }

    public function showAction($id) {
        $em = $this->getDoctrine()->getManager();
        $entity = $em->getRepository('AdminBundle:Empleado')->find($id);
        $html = $this->renderView('AdminBundle:Vehiculo:_partial_show_vehiculos.html.twig',
                array('vehiculos' => $entity->getVehiculos())
        );
        return new Response($html);
    }

    public function setTableTr($obj) {
        $linkActions = $this->renderView('AdminBundle:Vehiculo:_partial_linkactions.html.twig',
                array('vehiculo' => $obj)
        );
        $nombre = ($obj->getEmpleado()) ? $obj->getEmpleado()->getNombreCompleto() : '';
        $empleado = '<a href="#" class="show-modal" data-url="' . $this->generateUrl('vehiculo_update', array('id' => $obj->getId())) . '" title="Empleado Asignado" > ' . $nombre . ' </a>&nbsp;';
        return array(
            $obj->getDominio(),
            $obj->getMarca(),
            $obj->getModelo(),
            $obj->getAnio(),
            $obj->getLineasHtml(),
            $linkActions
        );
    }

}

src/SG/AdminBundle/Resources/views/Vehiculo/_partial_edit.html.twig
<style>
.modal-body {
    overflow-y:visible !important;
}
</style>
<form action="{{urlaction }}" id="formulario-modal" name="vehiculo" method="post" role="form" {{ form_enctype(form) }}>    
    
    {% include "AdminBundle::form-notification.html.twig" %}

    <fieldset>                            
        <div class="col-md-6">
            <div class="form-group">
                {{ form_row(form.dominio, { 'attr': {'class' : 'form-control' } }) }}
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                {{ form_row(form.anio, { 'attr': {'class' : 'form-control' } }) }}
            </div>
        </div>
         <div class="col-md-3">
            <div class="form-group">
                {{ form_row(form.carga, { 'attr': {'class' : 'form-control' } }) }}
            </div>
        </div>                                                                             
    </fieldset>                                                                      
    <fieldset>
        <div class="col-md-6">
            <div class="form-group">
                {{ form_row(form.marca, { 'attr': {'class' : 'form-control' } }) }}
            </div>
        </div> 
        <div class="col-md-6">
            <div class="form-group">
                {{ form_row(form.modelo, { 'attr': {'class' : 'form-control' } }) }}
            </div>
        </div>
    </fieldset>                                                                      
    <fieldset>
                                   
        <div class="col-md-4">
            <div class="form-group">
                {{ form_row(form.asignadoAlSocio) }}
            </div>                        
        </div>                                                                 
        <div class="col-md-8 empleado">
            <div class="form-group">
                {{ form_row(form.empleado, { 'attr': {'class' : 'form-control' } }) }}
            </div>
        </div>
    </fieldset>                                                                      
    <fieldset>
        
        <br>
        <table id="lineas" class="table table-bordered table-hover">
            <tbody data-index="{{form.lineas | length }}" class="collectionHolder"
                   data-prototype="{% filter escape %}{% include 'AdminBundle:Vehiculo:linea-prototype.html.twig' with {'item':form.lineas.vars.prototype} %}{% endfilter %}">
                {{ form_errors(form.lineas) }}
                <tr>
                    <th style="width: 5%">#</th>
                    <th style="width: 69%"> Líneas</th>
                    <th style="width: 20%"> Kilómetros</th>
                    <th style="width: 5%">
                        <button type="button" class="linkAddLinea" title="Agregar"><i class="fa fa-plus"></i></button>
                    </th>
                </tr>
                {% for item in form.lineas %}
                    <tr class="td">
                        <td class="ordTd"></td>                        
                        <td>{{ form_widget(item.nombre, { 'attr': {'class' : 'form-control' } }) }} </td>
                        <td>{{ form_widget(item.kilometros, { 'attr': {'class' : 'form-control alignright importe' } }) }}</td>
                        <td class="link-actions"> </td>
                    </tr>
                {% endfor %}
            </tbody>            
        </table>        
        
        
        
    </fieldset>                                                                                                                                            
       
    <div style="display:none">{{ form_rest(form) }}</div>

</form>    
<script type="text/javascript">    
$(document).ready(function() {
    $("#sg_adminbundle_vehiculo_empleado").chosen({
        no_results_text: "Sin resultados", 
        placeholder_text_single: 'Seleccione una opción' ,
        search_contains: true,
        allow_single_deselect:true});
    var emp = $("#sg_adminbundle_vehiculo_empleado").val();
    $.ajax({
        type: "POST",
        url: "{{ path('empleados_x_socio',{'id':entity.socio.id}) }}",
        contentType: "application/json; charset=utf-8",
        dataType: "json",
        success: function (data) {            
            $("#sg_adminbundle_vehiculo_empleado").html('');
            $("#sg_adminbundle_vehiculo_empleado").append( '<option value=""></option>' )
            $.each(data, function (idx, obj) {            
                $("#sg_adminbundle_vehiculo_empleado").append('<option value="' + obj.id + '">' + obj.apellido+', '+obj.nombre + '</option>');
            });
            $("#sg_adminbundle_vehiculo_empleado").val(emp);
            $("#sg_adminbundle_vehiculo_empleado").trigger("chosen:updated");
            $("#sg_adminbundle_vehiculo_empleado").chosen({ width: "95%" });
        },
        error: function (data) {
            console.log(data);
        }
    });
    
    $('#sg_adminbundle_vehiculo_asignadoAlSocio').on('change',function(){
        if( $(this).is(":checked") ){
            $('#sg_adminbundle_vehiculo_empleado').val('');
            $('#sg_adminbundle_vehiculo_empleado').trigger("chosen:updated");
            $('.empleado').hide();
        }else{
            $('.empleado').show();
        }
    });
    $('#sg_adminbundle_vehiculo_asignadoAlSocio').change();
    
    // LINEAS
    $('.linkAddLinea').on('click', function(e) {
        e.preventDefault();
        var holder = $('.collectionHolder');
        addNewItem(holder);
    });

    $('.collectionHolder').find('.link-actions').each(function() {
        addItemFormDeleteLink($(this));
    });
    setOrder();
    
});    
function addNewItem($collectionHolder) {
    var prototype = $collectionHolder.data('prototype');
    var index = $collectionHolder.data('index');
    var newForm = prototype.replace(/items/g, index);
    $collectionHolder.append(newForm);

    $collectionHolder.data('index', index + 1);
    $collectionHolder.find('.ordTd').last().html($collectionHolder.data('index'));
    addItemFormDeleteLink( $collectionHolder.find('.link-actions').last() );
}
function addItemFormDeleteLink($itemForm) {
    var $removeFormA = $('<button type="button" title="Eliminar"><i class="fa fa-trash"></i></button>');
    $itemForm.prepend($removeFormA);
    $removeFormA.on('click', function(e) {
        if ( confirm('Desea eliminar este item?') ) {
            e.preventDefault();
            $itemForm.parent().remove(); 
            setOrder();
            $('.collectionHolder').data('index', $('.collectionHolder').find('.ordTd').length );
        }
    });
}
function setOrder(){
    $('.collectionHolder').find('.ordTd').each(function(i) {        
        $(this).html(i + 1);
    });
}
</script>

src/SG/AdminBundle/Resources/views/Vehiculo/_partial_linkactions.html.twig
<button class="vehiculo-modal btn-inlist" data-url="{{path('vehiculo_render_modal')}}" data-id="{{ vehiculo.id }}" title="Datos del Vehículo" ><i class="fa fa-edit"></i></button>&nbsp;
{%if 'vehiculo-abm-delete' in app.user.perfil.permisos %}
<button class="delete-tab btn-inlist" data-url="{{path('vehiculo_delete', {'id':vehiculo.id})}}" title="Eliminar Vehículo" ><i class="fa fa-trash-o"></i></button>&nbsp;
{% endif %}
{% if vehiculo.empleado %}
<button class="show-modal btn-inlist" data-url="{{path('empleado_show', {'id':vehiculo.empleado.id})}}" title="Asignado a: {{ vehiculo.empleado.nombreCompleto }}" ><i class="fa fa-user"></i></button>&nbsp;
{% endif %}
{% if vehiculo.asignadoAlSocio %}
<i style="color:#444; font-size: 20px" title="Asignado al Socio" class="ion ion-person"></i>
{% endif %}

src/SG/AdminBundle/Resources/views/Vehiculo/_partial_list.html.twig
<fieldset>          
    <div class="col-md-12">

        <div class='box box-primary'>
            <div class='box-header'>
                <h3 class='box-title'><i class="fa fa-car"></i> &nbsp;Vehículos &nbsp&nbsp<span data-toggle="tooltip" title="Vehículos" id="vehiculos-count" class="badge bg-blue">{{ entity.vehiculos|length }}</span></h3>
                <div class="box-tools pull-right">
                    {%if 'vehiculo-abm-new' in app.user.perfil.permisos %}
                    <button type="button" id="vehiculo-add" class="btn btn-warning vehiculo-modal" data-toggle="tooltip" title="Nuevo Vehículo" data-url="{{path('vehiculo_render_modal')}}" data-socio="{{ entity.id }}"> 
                        <i class="fa fa-car"></i>&nbsp;&nbsp;Agregar
                    </button>
                    {% endif %}
                </div>
            </div><!-- /.box-header -->    
            <div class='box-body pad'>

                <div class="box-body table-responsive">
                    <table id="table-vehiculos" class="table table-bordered table-hover">
                    <thead>
                        <tr>                                
                            <th>Dominio</th>
                            <th>Marca</th>                                
                            <th>Modelo</th>                                
                            <th>Año</th>
                            <th>Líneas</th>
                            <th class="nosort" style="width: 120px"> <a class="hidden btn btn-sm btn-default" href="{{ path('socio_print_listado') }}" target="_blank"><i class="fa fa-print"></i> &nbsp;Listado</a> </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for vehiculo in entity.vehiculos %}
                            <tr class="data-{{ vehiculo.id }}" data-id="{{ vehiculo.id }}">
                                <td>{{ vehiculo.dominio }}</td>
                                <td>{{ vehiculo.marca }}</td>
                                <td>{{ vehiculo.modelo }}</td>
                                <td>{{ vehiculo.anio }}</td>
                                <td>
                                    {{ vehiculo.lineasHtml|raw }}                                                                        
                                </td>
                                <td class="link-actions">
                                    {% include "AdminBundle:Vehiculo:_partial_linkactions.html.twig" with {'id':vehiculo.id, 'empleado':vehiculo.empleado} %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>                    
                </div>


            </div>
        </div>

    </div>
</fieldset> 

src/SG/AdminBundle/Resources/views/Vehiculo/_partial_list_tr.html.twig
<tr class="data-{{ vehiculo.id }}" data-id="{{ vehiculo.id }}">
    <td>{{ vehiculo.dominio }}</td>
    <td>{{ vehiculo.marca }}</td>
    <td>{{ vehiculo.modelo }}</td>
    <td>{{ vehiculo.anio }}</td>
    <td>
        {{ vehiculo.lineasHtml|raw }}                                                                        
    </td>
    <td class="link-actions">
        {% include "AdminBundle:Vehiculo:_partial_linkactions.html.twig" with {'id':vehiculo.id, 'empleado':vehiculo.empleado} %}
    </td>
</tr>

src/SG/AdminBundle/Resources/views/Vehiculo/_partial_show_vehiculos.html.twig
<table class="table table-bordered table-hover tablelist">
    <thead>
        <tr>                                
            <th>#</th>
            <th>Dominio</th>
            <th>Marca</th>                                
            <th>Modelo</th>                                
            <th>Año</th>
            <th>Líneas</th>
            <th>Carga</th>
        </tr>
    </thead>
    <tbody>
        {% for vehiculo in vehiculos %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ vehiculo.dominio }}</td>
                <td>{{ vehiculo.marca }}</td>
                <td>{{ vehiculo.modelo }}</td>
                <td>{{ vehiculo.anio }}</td>
                <td>{{ vehiculo.lineasHtml|raw }}</td>
                <td>{{ vehiculo.carga }}</td>                
            </tr>
        {% endfor %}
    </tbody>
</table>
    
<script type="text/javascript">    
$(document).ready(function() {
    $('.modal-title').text('Vehículos asignados');
     $(".btn-success").hide();  
     $(".btn-danger").text('Cerrar');       
});    
</script>    

src/SG/AdminBundle/Resources/views/Vehiculo/linea-prototype.html.twig
<tr class="td">
    <td class="ordTd"></td>                        
    <td>{{ form_widget(item.nombre, { 'attr': {'class' : 'form-control' } }) }} </td>
    <td>{{ form_widget(item.kilometros, { 'attr': {'class' : 'form-control alignright importe' } }) }}</td>
    <td class="link-actions"> </td>
</tr>