src/SG/AdminBundle/Entity/CajaApertura.php
<?php

namespace SG\AdminBundle\Entity;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * SG\AdminBundle\Entity\CajaApertura
 * @ORM\Table(name="caja_apertura")
 * @ORM\Entity()
 */
class CajaApertura {
    /**
     * @var integer $id
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="SG\AdminBundle\Entity\Caja", inversedBy="aperturas")
     * @ORM\JoinColumn(name="caja_id", referencedColumnName="id")
     */
    protected $caja;

    /**
     * @var date $fechaApertura
     * @ORM\Column(name="fecha_apertura", type="datetime", nullable=false)
     */
    protected $fechaApertura;

    /**
     * @var integer $montoApertura
     * @ORM\Column(name="monto_apertura", type="decimal", scale=2 )
     */
    protected $montoApertura;

    /**
     * @var date $fechaCierre
     * @ORM\Column(name="fecha_cierre", type="datetime", nullable=true)
     */
    protected $fechaCierre;

    /**
     * @var integer $montoCierre
     * @ORM\Column(name="monto_cierre", type="decimal", scale=2, nullable=true )
     */
    protected $montoCierre;

    /**
     * @var User $updatedBy
     * @Gedmo\Blameable(on="update")
     * @ORM\ManyToOne(targetEntity="SG\ConfigBundle\Entity\Usuario")
     * @ORM\JoinColumn(name="updated_by", referencedColumnName="id")
     */
    private $updatedBy;

    /**
     * @var datetime $created
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @var User $createdBy
     * @Gedmo\Blameable(on="create")
     * @ORM\ManyToOne(targetEntity="SG\ConfigBundle\Entity\Usuario")
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
     */
    private $createdBy;

    /**
     * @ORM\OneToMany(targetEntity="SG\AdminBundle\Entity\CajaMovimiento", mappedBy="cajaApertura")
     */
    protected $movimientos;

    public function __toString() {
        return (string) $this->getId();
    }

    public function getTotalMovimientos() {
        $total = 0;
        foreach ($this->getMovimientos() as $mov) {
            if ($mov->getTipo() == 'I') {
                $total += $mov->getPago();
            }
            elseif ($mov->getTipo() == 'E') {
                $total -= $mov->getTotal();
            }
            else {
                foreach ($mov->getDetalles() as $det) {
                    if ($det->getConcepto()->getTipo() == 'L') {
                        $total -= $det->getImporte();
                    }
                    else {
                        $total += $det->getImporte();
                    }
                }
            }
        }

        return $total;
    }

    public function getDiferencia() {
        return ($this->getMontoApertura() + $this->getTotalMovimientos()) - $this->getMontoCierre();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set fechaApertura
     *
     * @param \DateTime $fechaApertura
     * @return CajaApertura
     */
    public function setFechaApertura($fechaApertura) {
        $this->fechaApertura = $fechaApertura;

        return $this;
    }

    /**
     * Get fechaApertura
     *
     * @return \DateTime
     */
    public function getFechaApertura() {
        return $this->fechaApertura;
    }

    /**
     * Set montoApertura
     *
     * @param string $montoApertura
     * @return CajaApertura
     */
    public function setMontoApertura($montoApertura) {
        $this->montoApertura = $montoApertura;

        return $this;
    }

    /**
     * Get montoApertura
     *
     * @return string
     */
    public function getMontoApertura() {
        return $this->montoApertura;
    }

    /**
     * Set fechaCierre
     *
     * @param \DateTime $fechaCierre
     * @return CajaApertura
     */
    public function setFechaCierre($fechaCierre) {
        $this->fechaCierre = $fechaCierre;

        return $this;
    }

    /**
     * Get fechaCierre
     *
     * @return \DateTime
     */
    public function getFechaCierre() {
        return $this->fechaCierre;
    }

    /**
     * Set montoCierre
     *
     * @param string $montoCierre
     * @return CajaApertura
     */
    public function setMontoCierre($montoCierre) {
        $this->montoCierre = $montoCierre;

        return $this;
    }

    /**
     * Get montoCierre
     *
     * @return string
     */
    public function getMontoCierre() {
        return $this->montoCierre;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     * @return CajaApertura
     */
    public function setCreated($created) {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime
     */
    public function getCreated() {
        return $this->created;
    }

    /**
     * Set caja
     *
     * @param \SG\AdminBundle\Entity\Caja $caja
     * @return CajaApertura
     */
    public function setCaja(\SG\AdminBundle\Entity\Caja $caja = null) {
        $this->caja = $caja;

        return $this;
    }

    /**
     * Get caja
     *
     * @return \SG\AdminBundle\Entity\Caja
     */
    public function getCaja() {
        return $this->caja;
    }

    /**
     * Set updatedBy
     *
     * @param \SG\ConfigBundle\Entity\Usuario $updatedBy
     * @return CajaApertura
     */
    public function setUpdatedBy(\SG\ConfigBundle\Entity\Usuario $updatedBy = null) {
        $this->updatedBy = $updatedBy;

        return $this;
    }

    /**
     * Get updatedBy
     *
     * @return \SG\ConfigBundle\Entity\Usuario
     */
    public function getUpdatedBy() {
        return $this->updatedBy;
    }

    /**
     * Set createdBy
     *
     * @param \SG\ConfigBundle\Entity\Usuario $createdBy
     * @return CajaApertura
     */
    public function setCreatedBy(\SG\ConfigBundle\Entity\Usuario $createdBy = null) {
        $this->createdBy = $createdBy;

        return $this;
    }

    /**
     * Get createdBy
     *
     * @return \SG\ConfigBundle\Entity\Usuario
     */
    public function getCreatedBy() {
        return $this->createdBy;
    }

    /**
     * Constructor
     */
    public function __construct() {
        $this->movimientos = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add movimientos
     *
     * @param \SG\AdminBundle\Entity\CajaMovimiento $movimientos
     * @return CajaApertura
     */
    public function addMovimiento(\SG\AdminBundle\Entity\CajaMovimiento $movimientos) {
        $this->movimientos[] = $movimientos;

        return $this;
    }

    /**
     * Remove movimientos
     *
     * @param \SG\AdminBundle\Entity\CajaMovimiento $movimientos
     */
    public function removeMovimiento(\SG\AdminBundle\Entity\CajaMovimiento $movimientos) {
        $this->movimientos->removeElement($movimientos);
    }

    /**
     * Get movimientos
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getMovimientos() {
        return $this->movimientos;
    }

}

src/SG/AdminBundle/Entity/Deuda.php
<?php

namespace SG\AdminBundle\Entity;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * SG\AdminBundle\Entity\Deuda
 * @ORM\Table(name="deuda")
 * @ORM\Entity(repositoryClass="SG\AdminBundle\Entity\DeudaRepository")
 */
class Deuda {
    /**
     * @var integer $id
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="SG\AdminBundle\Entity\Socio", inversedBy="deudas")
     * @ORM\JoinColumn(name="socio_id", referencedColumnName="id", onDelete="SET NULL")
     */
    protected $socio;

    /**
     * @ORM\ManyToOne(targetEntity="SG\ConfigBundle\Entity\ConceptoCaja")
     * @ORM\JoinColumn(name="concepto_caja_id", referencedColumnName="id")
     */
    protected $concepto;

    /**
     * @var string $descripcion
     * @ORM\Column(name="descripcion", type="text", nullable=true)
     */
    protected $descripcion;

    /**
     * @var string $detalle
     * @ORM\Column(name="detalle", type="text", nullable=true)
     */
    protected $detalle;

    /**
     * @var date $fechaVto
     * @ORM\Column(name="fecha_vto", type="datetime", nullable=false)
     */
    protected $fechaVto;

    /**
     * @var integer $monto
     * @ORM\Column(name="monto", type="decimal", scale=2 )
     */
    protected $monto = 0;

    /**
     * @var integer $mora
     * @ORM\Column(name="mora", type="decimal", scale=2 )
     */
    protected $mora = 0;

    /**
     * @ORM\OneToMany(targetEntity="SG\AdminBundle\Entity\Pago", mappedBy="deuda",cascade={"persist", "remove"})
     */
    protected $pagos;

    /**
     * @var string $cancelada
     * @ORM\Column(name="cancelada", type="boolean")
     */
    protected $cancelada = false;

    /**
     * @var date $fechaCancelacion
     * @ORM\Column(name="fecha_cancelacion", type="datetime", nullable=true)
     */
    protected $fechaCancelacion;

    /**
     * @ORM\OneToMany(targetEntity="SG\AdminBundle\Entity\CajaMovimientoDetalle", mappedBy="deuda")
     */
    protected $movimientos;

    /**
     * @var datetime $created
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @var User $createdBy
     * @Gedmo\Blameable(on="create")
     * @ORM\ManyToOne(targetEntity="SG\ConfigBundle\Entity\Usuario")
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
     */
    private $createdBy;

    /**
     * Constructor
     */
    public function __construct() {
        $this->pagos = new \Doctrine\Common\Collections\ArrayCollection();
    }

    public function getDeudaTxt() {
        return $this->concepto . ' - ' . $this->descripcion;
    }

    public function getSaldo() {
        $saldo = $this->monto + $this->mora;
        foreach ($this->getPagos() as $pago) {
            $saldo = $saldo - $pago->getImporte();
        }
        if ($this->getConcepto()->getTipo() == 'L') {
            $monto = 0;
            // restar los items descontados en la liquidación.
            foreach ($this->getMovimientos() as $detmov) {
                $monto = $monto + $detmov->getCajaMovimiento()->getLiquidacionImputaciones();
            }
            $saldo = $saldo - $monto;
        }
        return ($saldo < 0) ? 0 : $saldo;
    }

    public function getUltimoPago() {
        $fecha = null;
        foreach ($this->getPagos() as $pago) {
            $fecha = $pago->getFecha();
        }
        return $fecha;
    }

    public function getVencido() {
        $hoy = new \DateTime;
        return ($this->fechaVto->format('Ymd') < $hoy->format('Ymd')) && ($this->getSaldo() > 0);
    }

    public function getTotal() {
        return $this->monto + $this->mora;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set fechaVto
     *
     * @param \DateTime $fechaVto
     * @return Deuda
     */
    public function setFechaVto($fechaVto) {
        $this->fechaVto = $fechaVto;

        return $this;
    }

    /**
     * Get fechaVto
     *
     * @return \DateTime
     */
    public function getFechaVto() {
        return $this->fechaVto;
    }

    /**
     * Set monto
     *
     * @param string $monto
     * @return Deuda
     */
    public function setMonto($monto) {
        $this->monto = $monto;

        return $this;
    }

    /**
     * Get monto
     *
     * @return string
     */
    public function getMonto() {
        return $this->monto;
    }

    /**
     * Set mora
     *
     * @param string $mora
     * @return Deuda
     */
    public function setMora($mora) {
        $this->mora = $mora;

        return $this;
    }

    /**
     * Get mora
     *
     * @return string
     */
    public function getMora() {
        return $this->mora;
    }

    /**
     * Set cancelada
     *
     * @param boolean $cancelada
     * @return Deuda
     */
    public function setCancelada($cancelada) {
        $this->cancelada = $cancelada;

        return $this;
    }

    /**
     * Get cancelada
     *
     * @return boolean
     */
    public function getCancelada() {
        return $this->cancelada;
    }

    /**
     * Set fechaCancelacion
     *
     * @param \DateTime $fechaCancelacion
     * @return Deuda
     */
    public function setFechaCancelacion($fechaCancelacion) {
        $this->fechaCancelacion = $fechaCancelacion;

        return $this;
    }

    /**
     * Get fechaCancelacion
     *
     * @return \DateTime
     */
    public function getFechaCancelacion() {
        return $this->fechaCancelacion;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     * @return Deuda
     */
    public function setCreated($created) {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime
     */
    public function getCreated() {
        return $this->created;
    }

    /**
     * Set concepto
     *
     * @param \SG\ConfigBundle\Entity\ConceptoCaja $concepto
     * @return Deuda
     */
    public function setConcepto(\SG\ConfigBundle\Entity\ConceptoCaja $concepto = null) {
        $this->concepto = $concepto;

        return $this;
    }

    /**
     * Get concepto
     *
     * @return \SG\ConfigBundle\Entity\ConceptoCaja
     */
    public function getConcepto() {
        return $this->concepto;
    }

    /**
     * Add pagos
     *
     * @param \SG\AdminBundle\Entity\Pago $pagos
     * @return Deuda
     */
    public function addPago(\SG\AdminBundle\Entity\Pago $pagos) {
        $this->pagos[] = $pagos;

        return $this;
    }

    /**
     * Remove pagos
     *
     * @param \SG\AdminBundle\Entity\Pago $pagos
     */
    public function removePago(\SG\AdminBundle\Entity\Pago $pagos) {
        $this->pagos->removeElement($pagos);
    }

    /**
     * Get pagos
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPagos() {
        return $this->pagos;
    }

    /**
     * Set createdBy
     *
     * @param \SG\ConfigBundle\Entity\Usuario $createdBy
     * @return Deuda
     */
    public function setCreatedBy(\SG\ConfigBundle\Entity\Usuario $createdBy = null) {
        $this->createdBy = $createdBy;

        return $this;
    }

    /**
     * Get createdBy
     *
     * @return \SG\ConfigBundle\Entity\Usuario
     */
    public function getCreatedBy() {
        return $this->createdBy;
    }

    /**
     * Set socio
     *
     * @param \SG\AdminBundle\Entity\Socio $socio
     * @return Deuda
     */
    public function setSocio(\SG\AdminBundle\Entity\Socio $socio = null) {
        $this->socio = $socio;

        return $this;
    }

    /**
     * Get socio
     *
     * @return \SG\AdminBundle\Entity\Socio
     */
    public function getSocio() {
        return $this->socio;
    }

    /**
     * Set descripcion
     *
     * @param string $descripcion
     * @return Deuda
     */
    public function setDescripcion($descripcion) {
        $this->descripcion = $descripcion;

        return $this;
    }

    /**
     * Get descripcion
     *
     * @return string
     */
    public function getDescripcion() {
        return $this->descripcion;
    }

    /**
     * Set detalle
     *
     * @param string $detalle
     * @return Deuda
     */
    public function setDetalle($detalle) {
        $this->detalle = $detalle;

        return $this;
    }

    /**
     * Get detalle
     *
     * @return string
     */
    public function getDetalle() {
        return $this->detalle;
    }

    /**
     * Add movimientos
     *
     * @param \SG\AdminBundle\Entity\CajaMovimientoDetalle $movimientos
     * @return Deuda
     */
    public function addMovimiento(\SG\AdminBundle\Entity\CajaMovimientoDetalle $movimientos) {
        $this->movimientos[] = $movimientos;

        return $this;
    }

    /**
     * Remove movimientos
     *
     * @param \SG\AdminBundle\Entity\CajaMovimientoDetalle $movimientos
     */
    public function removeMovimiento(\SG\AdminBundle\Entity\CajaMovimientoDetalle $movimientos) {
        $this->movimientos->removeElement($movimientos);
    }

    /**
     * Get movimientos
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getMovimientos() {
        return $this->movimientos;
    }

}

src/SG/AdminBundle/Resources/views/Caja/_partial_lista_movimientos.html.twig
<div class="box-body table-responsive">
    <table id="tablelist" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th class="nosort" style="width:15px">&nbsp;#</th>
                <th class="nosort" style="width:70px">Fecha</th>
                <th class="nosort" style="width:15px">Hora</th>
                <th class="nosort" >Descripción</th>
                <th class="nosort center" style="width:100px">Debe</th>
                <th class="nosort center" style="width:100px">Haber</th>
                <th class="nosort center" style="width:100px">Saldo</th> 
                <th class="nosort" style="width:20px"></th>
                <th class="nosort" style="width:85px"></th>
            </tr>
        </thead>
        <tbody>
            {% set saldo,debe,haber=apertura.montoApertura,apertura.montoApertura,0 %}
            <tr>
                <td></td>
                <td>{{ apertura.fechaApertura|date('d-m-Y') }}</td>
                <td>{{ apertura.fechaApertura|date('H:i') }}</td>
                <td>Apertura de Caja</td>
                <td></td>
                <td class="alignright">{{apertura.montoApertura|number_format(2,'.',',')}}</td>
                <td class="alignright">{{apertura.montoApertura|number_format(2,'.',',')}}</td>
                <td></td>
                <td></td>
            </tr>
            {% if apertura.movimientos|length>0 %}
            {% for movimiento in apertura.movimientos %}
                <tr class="odd gradeX">
                    <td>
                        {% if movimiento.tipo == 'I' %}
                            {% set saldo= saldo+movimiento.pago%}
                            {# set haber= haber+movimiento.pago #}
                            <img src="{{ asset('assets/img/in.png') }}" style="margin-top: 5px"/>
                        {% else %}
                            {% if movimiento.tipo == 'L' %}
                                {% set saldo= saldo-movimiento.detalleLiquidacion.importe%}
                                {% set saldo= saldo+movimiento.liquidacionImputaciones%}
                                {# set debe= debe+movimiento.pago #}
                            {% else %}    
                                {% set saldo= saldo-movimiento.total%}
                                {# set debe= debe+movimiento.total #}
                            {% endif %}                                
                            <img src="{{ asset('assets/img/out.png') }}" style="margin-top: 5px"/>                                    
                        {% endif %}                        
                        
                    </td>
                    <td>{{ movimiento.fecha|date('d-m-Y') }}</td>
                    <td>{{ movimiento.fecha|date('H:i') }}</td>
                    <td>
                        {% if  movimiento.descripcion is null %} 
                            {% if movimiento.tipo == 'E' %}
                                Salida de Caja                                    
                            {% else %}
                                {{ movimiento.responsablePago }}
                            {% endif %}
                        {% else %}
                            {{movimiento.descripcion}}
                        {% endif %}
                    </td>
                    <td class="alignright">{% if movimiento.tipo == 'E' %} {{movimiento.total|number_format(2,'.',',')}} {% elseif  movimiento.tipo == 'L' %} {{movimiento.detalleLiquidacion.importe|number_format(2,'.',',')}}  {% endif %}</td>
                    <td class="alignright">{% if movimiento.tipo == 'I' %}{{movimiento.pago|number_format(2,'.',',')}} {% elseif  movimiento.tipo == 'L' %} {{movimiento.liquidacionImputaciones|number_format(2,'.',',')}}  {% endif %}</td>
                    <td class="alignright">{{saldo|number_format(2,'.',',')}}</td>
                    <td><button type="button" class="vermas" id="{{movimiento.id}}" style="margin: 0" title="Ver detalle" ><i class="fa fa-caret-down"></i></button></td>
                    <td>
                        {% if apertura.fechaCierre is null and movimiento.tipo != 'L' %}
                            <form action="{{ path('caja_movimiento_delete', { 'id': movimiento.id }) }}" method="post" class="form-delete-inlist">
                                <input type="hidden" name="_method" value="DELETE" />
                                {{ form_widget(deleteForms[movimiento.id]) }}
                                <button type="button" title="Eliminar" class="borrar"><i class="fa fa-trash"></i></button>
                            </form>    
                        {% endif %}    
                        <button type="button" class="comprobante" data-url="{{ path('caja_print_movimiento', { 'id': movimiento.id })  }}" style="margin: 0" title="Imprimir" ><i class="fa fa-file-text-o"></i></button>
                    </td>
                </tr>
                <tr class="even" id="tr_detalle_{{movimiento.id~movimiento.tipo}}" data-tipo="{{movimiento.tipo}}">
                    <td></td>
                    <td colspan="7" class="datos_detalle"></td>
                    <td></td>
                </tr>
            {% endfor %}
            {% else %}
                <tr>
                    <th colspan="9" class="aligncenter"> -- SIN MOVIMIENTOS --</th>
                </tr>
            {% endif %}            
        </tbody>
    </table>
</div>    

src/SG/AdminBundle/Resources/views/Caja/informe-cierre.html.twig
{% extends "AdminBundle::layout.html.twig" %}
{% block contentheader %}
<h1>Cierre de Caja N° {{apertura.id}}</h1>
{% endblock %}

{% block content %}
<div class='row'>
    <div class='col-md-12'>
        <div class='box box-solid box-primary'>
            <div class='box-header'>
                <h3 class='box-title'><i class="fa fa-money"></i> &nbsp;Caja {{apertura.caja.nombre}}</h3>
            </div><!-- /.box-header -->
            <div class='box-body pad'>
                <div class="box-body table-responsive">

                    <form action="#">
                        <div class='box-body pad'>
                            {% include "AdminBundle::form-notification.html.twig" %}          
                            <fieldset>             
                                <div class="col-md-3">
                                    <div class="form-group alignright">
                                        <label>Fecha y Hora Aperturax:</label>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <input value="{{apertura.fechaApertura|date('d/m/Y  H:i')}}" class="form-control" disabled="disabled">
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group alignright">
                                        <label>Fecha y Hora Cierre:</label>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <input value="{{apertura.fechaCierre|date('d/m/Y  H:i')}}" class="form-control" disabled="disabled">
                                    </div>
                                </div>
                            </fieldset>
                                    <br>
                            <fieldset>             
                                <div class="col-md-3">&nbsp;</div>
                                <div class="col-md-2">
                                    <div class="form-group alignright">
                                        <label>Monto Apertura:</label>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <input value="{{ apertura.montoApertura|number_format(2,'.',',') }}" class="form-control alignright" disabled="disabled">
                                    </div>
                                </div>
                            </fieldset>
                            <fieldset>             
                                <div class="col-md-3">&nbsp;</div>
                                <div class="col-md-2">
                                    <div class="form-group alignright">
                                        <label>Movimientos:</label>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <input value="{{ apertura.totalMovimientos|number_format(2,'.',',') }}" class="form-control alignright" disabled="disabled">
                                    </div>
                                </div>
                            </fieldset>
                                    
                            <fieldset>             
                                <div class="col-md-3">&nbsp;</div>
                                <div class="col-md-4">
                                    <hr>
                                </div>
                            </fieldset>
                            <fieldset>             
                                <div class="col-md-3">&nbsp;</div>
                                <div class="col-md-2">
                                    <div class="form-group alignright">
                                        <label>TOTAL:</label>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <input value="{{ (apertura.montoApertura + apertura.totalMovimientos)|number_format(2,'.',',') }}" class="form-control alignright" disabled="disabled">
                                    </div>
                                </div>
                            </fieldset>
                            <fieldset>             
                                <div class="col-md-3">&nbsp;</div>
                                <div class="col-md-2">
                                    <div class="form-group alignright">
                                        <label>Monto en Caja:</label>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <input value="{{ apertura.montoCierre|number_format(2,'.',',') }}" class="form-control alignright" disabled="disabled">
                                    </div>
                                </div>
                                <div class="col-md-5 alignright">
                                    <a class="pull-right btn btn-default" href="{{path('caja_aperturacierre')}}" data-toggle="tooltip" title="Imprimir Informe"><i class="fa fa-reply"></i>&nbsp;&nbsp;Volver</a>
                                    <a class="pull-right btn btn-primary" href="{{path('caja_print_cierre', { 'id': apertura.id })}}" target="_blank" style="margin-right: 10px;" ><i class="fa fa-print"></i>&nbsp;&nbsp;Imprimir</a>
                                </div>
                                    
                            </fieldset>
                            <fieldset>             
                                <div class="col-md-3">&nbsp;</div>
                                <div class="col-md-2">
                                    <div class="form-group alignright">
                                        <label>DIFERENCIA:</label>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <input value="{{ apertura.diferencia|number_format(2,'.',',') }}" class="form-control alignright {% if apertura.diferencia!=0 %}red{%endif%}" disabled="disabled">
                                    </div>
                                </div>                                    
                            </fieldset>
                        </div>
                    </form>                                    
                                    
                    <div class="box box-warning">
                        <div class="box-header">
                            <h3 class="box-title">Detalle de Movimientos</h3>
                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-warning btn-sm" data-widget="collapse"><i class="fa fa-minus"></i></button>
                            </div>
                        </div>
                        <div class="box-body no-padding">
                            {% include "AdminBundle:Caja:_partial_lista_movimientos.html.twig" %}                       
                        </div><!-- /.box-body -->
                    </div><!-- /.box -->                                        
                                    
                </div>
            </div>
        </div><!-- /.box -->
    </div><!-- /.col-->
</div><!-- ./row -->           

{% endblock %}
{% block page_javascript %}
<script type="text/javascript">
$(document).ready(function(){
    $('[id*="tr_detalle_"]').hide();
    $('.vermas').click(function(){
        id = $(this).attr('id');
        trDetalle = $(this).parent().parent().next();
        tipoDetalle = trDetalle.data('tipo');            
        if( $(this).hasClass('cerrar') ){
            //trDetalle.find('.datos_detalle').html('');
            $(this).removeClass('cerrar');
            $(this).html('<i class="fa fa-caret-down"></i>');
        }else{ 
            if(trDetalle.find('.datos_detalle').html()==''){
                //traer datos
                $.get("{{path('caja_movimiento_getDetalle')}}", { id: id, tipo: tipoDetalle })
                    .done(function( data ) {
                        trDetalle.find('.datos_detalle').html(data);
                });        
            }
            $(this).addClass('cerrar');
            $(this).html('<i class="fa fa-caret-up"></i>');
        } 
        trDetalle.fadeToggle("slow");

    });       
});
</script>
{% endblock %}